name: Monitor Consulado
on:
  schedule:
    - cron: '*/30 * * * *' # Se ejecuta cada 30 minutos
  workflow_dispatch: # Permite ejecutarlo a mano para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install "httpx<0.28.0"
      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python script.py
      - name: Save state
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@github.com'
          git add last_hash.txt
          git commit -m "Update hash" || exit 0
          git push
